version: '2'

services:
    nginx:
        image: nginx:1.19.9-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./webserver-config/apigateway.default.conf:/etc/nginx/conf.d/default.conf
            - ./src/fe/shell/dist/shell:/usr/share/nginx/html/shell
            - ./src/fe/mf1/dist/eurofins-app:/usr/share/nginx/html/mf1
            - ./src/fe/mf2/dist/eurofins-app:/usr/share/nginx/html/mf2
    todo-api-v1:
        build:
            context: ./src/api/todo-api-v1
        volumes:
            - ./src/api/todo-api-v1/todo-api/:/app/db/
        ports:
            - 8090:80
    todo-api-v2:
        build:
            context: ./src/api/todo-api-v2
        volumes:
            - ./src/api/todo-api-v2/todo-api/:/app/db/
        ports:
            - 8091:80